@startuml
'数据库,客户,图标
class OCustomerDataChart {
'连接数据库
Connection getConnection()
'查询所有客户信息
List findCustomers()
'创建图表
void createChart()
'显示图表
void displayChart()
}

'单一职责原则
'1.数据库
class DBUtil {
Connection getConnection()
}
'2.客户
class CustomerDao {
DBUtil util
List findCustomers()
}
'3.图表
class CustomerDataChart {
CustomerDao dao
void createChart()
void displayChart()
}
'成员变量
CustomerDao --down> DBUtil
CustomerDataChart --right> CustomerDao

@enduml