@startuml
class Client
interface CustomerDataDisplay{
dataRead()
transformToXML()
createChart()
displayChart()
createReport()
displayReport()
}
Client ..right> CustomerDataDisplay

class ConcreteClass {
dataRead()
transformToXML()
createChart()
displayChart()
createReport()
displayReport()
}
ConcreteClass ..up|> CustomerDataDisplay

@enduml