server:
  port: 9010
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/skeleton?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true
    username: root
    password: Wusd123..
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
mybatis:
  mapper-locations: classpath:mapper/**/*.xml