spring:
  shardingsphere:
    props:
      sql-show: true
      rewrite-bindings: false
    datasource:
      names: m1
      m1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${wsl-ip}:3306/order_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
        username: root
        password: Wusd123..
    rules:
      sharding:
        tables:
          t_order:
            actual-data-nodes: m1.t_order_$->{1..2}
            table-strategy:
              standard:
                sharding-column: order_id
                sharding-algorithm-name: t_order_inline
            key-generate-strategy:
              column: order_id
              key-generator-name: snowflake
        sharding-algorithms:
          t_order_inline:
            type: INLINE
            props:
              algorithm-expression: t_order_$->{order_id % 2 + 1}
        key-generators:
          snowflake:
            type: SNOWFLAKE