wsl-ip: 172.23.141.84
#wsl-ip: 172.24.248.215

server:
  port: 9010
  servlet:
    encoding:
      enabled: true
      charset: utf-8
      force: true

spring:
  profiles:
    active: develop,redis,mybatis,rocketmq,horizontal
  main:
    allow-bean-definition-overriding: true
knife4j:
  enable: true
logging:
  level:
    root: info
    com.wusd.skeleton: debug
    org.apache.shardingsphere: debug
  config: classpath:logback-spring.xml